Done and tested, see sample output below
**************************************************
* UNIT TESTS
**************************************************
==================================================
SCRAPER UNIT TESTS
..[Thread 1] An Error occurred while trying to search for Macbeth 'bool' object has no attribute 'ChromeOptions'
F..d:\Work\Masters_Phd\workspace (GradSchool)\ece651-project\src\scraper\test_webdriver.py:14: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(chrome_options=options)

DevTools listening on ws://127.0.0.1:19737/devtools/browser/84e49f41-539d-4b1f-878b-9286ccb342d6
.
======================================================================
FAIL: test_search_1984 (test_amazon_requests.TestAmazonRequests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\Work\Masters_Phd\workspace (GradSchool)\ece651-project\src\scraper\test_amazon_requests.py", line 40, in test_search_1984
    self.assertIsNotNone(book_url)
AssertionError: unexpectedly None

----------------------------------------------------------------------
Ran 6 tests in 10.197s

FAILED (failures=1)
==================================================

==================================================
ML UNIT TESTS

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
==================================================

==================================================
WEB UNIT TESTS

> web@0.0.0 test d:\Work\Masters_Phd\workspace (GradSchool)\ece651-project\src\web
> mocha

  Array
    #indexOf()
      √ should return -1 when the value is not present

  1 passing (7ms)

==================================================

**************************************************
* UNIT TESTS
**************************************************
==================================================
WEB SYSTEM TESTS

DevTools listening on ws://127.0.0.1:19773/devtools/browser/81c15f30-e0eb-4fa0-8703-8939a0f39ac4
E
DevTools listening on ws://127.0.0.1:19799/devtools/browser/9786947d-31f3-43d6-99a5-227198a422f3
E
======================================================================
ERROR: test_signin (test_signin.TestSignInUpSystem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\Work\Masters_Phd\workspace (GradSchool)\ece651-project\src\web\test\gui_tests\test_signin.py", line 19, in test_signin
    elem.click()
AttributeError: 'NoneType' object has no attribute 'click'

======================================================================
ERROR: test_signup (test_signup.TestSignInUpSystem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\Work\Masters_Phd\workspace (GradSchool)\ece651-project\src\web\test\gui_tests\test_signup.py", line 20, in test_signup
    elem.send_keys("Test User01")
AttributeError: 'NoneType' object has no attribute 'send_keys'

----------------------------------------------------------------------
Ran 2 tests in 24.393s

FAILED (errors=2)
==================================================